version: 2
general:
  branches:
    only:
      - main
      - master
jobs:
  build:
    docker:
      - image: circleci/node:14.15.0-browsers
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
          echo "hello world"